import localFont from 'next/font/local';
import { ThemeProvider } from 'next-themes';

import './globals.css';

const inter = localFont({
  src: [
    {
      path: '../fonts/Inter-Regular.woff2',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../fonts/Inter-Medium.woff2',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../fonts/Inter-SemiBold.woff2',
      weight: '600',
      style: 'normal'
    },
    {
      path: '../fonts/Inter-Bold.woff2',
      weight: '700',
      style: 'normal'
    },
    {
      path: '../fonts/Inter-ExtraBold.woff2',
      weight: '800',
      style: 'normal'
    }
  ],
  display: 'swap',
  variable: '--font-inter',
  adjustFontFallback: false
});

export const metadata = {
  title: 'Billboard Marketplace',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body className={`${inter.variable}`}>
        <ThemeProvider enableSystem={false}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
