import { Inter } from 'next/font/google';
import { ThemeProvider } from 'next-themes';

import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-inter',
  display: 'swap'
});

export const metadata = {
  title: 'Billboard Marketplace',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body className={`${inter.variable}`}>
        <ThemeProvider enableSystem={false}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
